language: python
python:
  - "2.7"
env:
  - APP_SETTINGS=config.DevelopmentConfig
  - DATABASE_URL=postgresql://localhost/testapp
  
# command to install dependencies
install:
  - pip install -r requirements.txt
